displayName: Traefik OIDC
type: middleware

import: github.com/lukaszraczylo/traefikoidc

summary: |
  WIP [do not use, yet] Middleware adding OIDC authentication to traefik.

testData:
  providerURL: https://accounts.google.com
  clientID: 1234567890.apps.googleusercontent.com
  clientSecret: secret
  callbackURL: https://example.com/oauth2/callback
  scopes:
    - openid
    - email
    - profile
  sessionEncryptionKey: potato-secret
